# Generated by Django 4.1.10 on 2023-09-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Customer',
        ),
    ]
